### ISSUE TITLE
[1.12.2] - Mantle Config is missing?

### ISSUE THREAD

**Issue by Z-Tunic** [SlimeKnights/Mantle#102]
Minecraft: 1.12.2
Forge: 14.23.2.2629

Mods:
Mantle-1.12-1.3.1.21

Info:
Was going to see if there was a way to disable the custom hearts render after finding out it was in Mantle and to check the config for it, but... I can't seem to find the config file for it.

I did a fresh reload of the config files on a different copy of Minecraft for testing purposes and with only the Mantle mod installed. Apparently the mantle config isn't generating. Is this suppose to happen?

Also... in case the option isn't in the config file, can there be a way to disable the custom heart render?

**Comment by bonii-xx** [comment]
There is no config, since mantle doesn't contain any standalone features besides the hearts. The hearts can be disabled by other mods by consuming the appropriate heart render event. It's not possible to have vanilla heart rendering with mantle present.

**Comment by Z-Tunic** [comment]
If a toggle can't be added then can this be fixed by any chance if you have more than 150 Hearts? The custom hearts render from Mantle seems to only go up to 120 hearts then it just stays white until you go above 150 Hearts... then it starts to bug out and it worsens if a player has more health for whatever reason.
![](https://cdn.discordapp.com/attachments/377171551155650560/428677089244479489/mantleheartoverflow.PNG)

**Comment by bonii-xx** [comment]
Curious. I think the colors should just wrap around in that case. Sounds like a bug, even though having 150 hearts is not something that should exist in any case ;P

**Comment by bonii-xx** [comment]
There we go. All fixed up. It'll just loop back to the first (orange, not vanilla red) color now and continue. By the way, if you had that many hearts with vanilla, you'd have 12 rows of hearts. I doubt you'd like that any better ;)

**Comment by joeyjumper94** [comment]
this is still a problem for me
i am FORCED to use this by tinkers construct in 1.12.2 but would want the vanilla heart overlay so that if i have more then 20 max HP, i can see it, not that it is hidden

**Comment by KnightMiner** [comment]
The heart renderer works fine on 1.12 as of the resolution of this issue. I am sorry you cannot disable it, that option was never added to 1.12. If you update to a supported version like 1.18 there is a config option to disable it. There will be no further changes to 1.12.
